using Mutagen.Bethesda;
using Mutagen.Bethesda.Oblivion;
using Mutagen.Bethesda.Plugins.Exceptions;
using Mutagen.Bethesda.Synthesis;

namespace TMPatcher
{
    public class Program
    {
        private static Lazy<Settings> _settings = null!;
        private static Settings Settings => _settings.Value;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<IOblivionMod, IOblivionModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.Oblivion, "TMPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<IOblivionMod, IOblivionModGetter> state)
        {
            Console.WriteLine("\n\nRunPatch`Open\n");
            Console.WriteLine($"Settings.FeatureGuaranteeOneIngredientEffect:{Settings.FeatureGuaranteeOneIngredientEffect}");
            // FeatureGuaranteeOneIngredientEffect
            if (Settings.FeatureGuaranteeOneIngredientEffect)
            {
                // TODO: Find a better way to get an effect. Also, it might be better to get a different effect, like restore fatigue.
                IEffectGetter? nullableEffect = null;
                foreach (var ingredient in state.LoadOrder.PriorityOrder.WinningOverrides<IIngredientGetter>())
                {
                    try
                    {
                        Console.WriteLine("Before getting effect.");
                        nullableEffect = ingredient.Effects[0];
                        Console.WriteLine("After getting effect.");
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Couldn't get effect from ingredient.");
                    }
                }
                var effect = nullableEffect!;
                
                foreach (var oldIngredient in state.LoadOrder.PriorityOrder.WinningOverrides<IIngredientGetter>())
                {
                    try
                    {
                        if (oldIngredient.Effects.Count > 0)
                        {
                            Console.WriteLine($"Skipping ingredient because Count > 0. EditorID:{oldIngredient.EditorID} Name:{oldIngredient.Name}");
                            continue;
                        }

                        var newIngredient = oldIngredient.DeepCopy();
                        newIngredient.Effects.Add(effect.DeepCopy());
                        state.PatchMod.Ingredients.Set(newIngredient);
                        Console.WriteLine($"Modified ingredient. EditorID:{newIngredient.EditorID} Name:{newIngredient.Name}");
                    }
                    catch (Exception ex)
                    {
                        throw RecordException.Enrich(ex, oldIngredient);
                    }
                }
            }
            Console.WriteLine("\n\nRunPatch`Close\n");
        }
    }
}
